import{a as y,S as h,i as d}from"./assets/vendor-89feecc5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const L=y.create({baseURL:"https://pixabay.com/api/",params:{key:"41686068-f8a1ddec694d7ca7a5960473b",image_type:"photo",orientation:"horizontal",safesearch:!0}}),b=()=>d.warning({position:"topRight",message:"Please, fill in the field!"}),v=()=>d.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),p=document.querySelector(".gallery"),w=document.querySelector(".search-form"),l=document.querySelector(".loading"),i=document.querySelector(".btn-load");function x(a=[]){const t=a.reduce((r,{largeImageURL:n,webformatURL:e,tags:s,likes:c,views:f,comments:g,downloads:m})=>r+`<li class="gallery-item">
    <a href=${n}> 
      <img class="gallery-img" src =${e} alt=${s}/>
    </a>
    <div class="gallery-text-box">
      <p>Likes: <span class="text-value">${c}</span></p>
      <p>views: <span class="text-value">${f}</span></p>
      <p>comments: <span class="text-value">${g}</span></p>
      <p>downloads: <span class="text-value">${m}</span></p>
  </div>
  </li>`,"");p.insertAdjacentHTML("beforeend",t),S.refresh()}const S=new h(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0}),q=async a=>{try{return(await L.get("",{params:a})).data}catch(t){console.error(t)}},H=a=>{let t=1,r=!1;const n=40;return async()=>{try{if(r)return;const{hits:e,totalHits:s}=await q({page:t,per_page:n,q:a});if(t>=Math.ceil(s/n)&&(r=!0),t++,r&&(i.style.display="none"),e.length==0){v();return}return e}catch(e){console.error(e)}}};let o=null;w.addEventListener("submit",async a=>{a.preventDefault(),o!=null&&(i.removeEventListener("click",o),o=null);const r=new FormData(a.currentTarget).get("search");if(!r){b();return}p.innerHTML="",i.style.display="block";const n=H(r);a.currentTarget.reset(),o=async()=>{const e=await u({promise:n,spinner:l});x(e)},await u({promise:o,spinner:l}),i.addEventListener("click",o)});const u=async({promise:a,spinner:t,className:r="is-hidden"})=>{t.classList.remove(r),i.classList.add(r);const n=await a();return t.classList.add(r),i.classList.remove(r),n};
//# sourceMappingURL=commonHelpers.js.map
