import{a as y,S as h}from"./assets/vendor-ec3f2df4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const g=y.create({baseURL:"https://pixabay.com/api/",params:{key:"41686068-f8a1ddec694d7ca7a5960473b",image_type:"photo",orientation:"horizontal",safesearch:!0}}),u=document.querySelector(".gallery"),L=document.querySelector(".search-form");document.querySelector(".loading");const i=document.querySelector(".btn-load"),l=document.querySelector(".load-more-spinner");function v(s=[]){const t=s.reduce((n,{largeImageURL:o,webformatURL:e,tags:r,likes:c,views:p,comments:m,downloads:f})=>n+`<li class="gallery-item">
    <a href=${o}> 
      <img class="gallery-img" src =${e} alt=${r}/>
    </a>
    <div class="gallery-text-box">
      <p>Likes: <span class="text-value">${c}</span></p>
      <p>views: <span class="text-value">${p}</span></p>
      <p>comments: <span class="text-value">${m}</span></p>
      <p>downloads: <span class="text-value">${f}</span></p>
  </div>
  </li>`,"");u.insertAdjacentHTML("beforeend",t),b.refresh()}const b=new h(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0}),w=async s=>{try{return(await g.get("",{params:s})).data}catch(t){console.error(t)}},x=s=>{let t=1,n=!1;const o=3;return async()=>{try{if(n)return[];const{hits:e,totalHits:r}=await w({page:t,per_page:o,q:s});return t>=Math.ceil(r/o)&&(n=!0),t++,e}catch(e){console.error(e)}}};let a=null;L.addEventListener("submit",async s=>{s.preventDefault(),a!=null&&(i.removeEventListener("click",a),i.classList.add("is-hidden"),a=null);const n=new FormData(s.currentTarget).get("search");u.innerHTML="";const o=x(n);a=async()=>{const e=await d({promise:o,spinner:l});v(e)},await d({promise:a,spinner:l}),i.classList.remove("is-hidden"),i.addEventListener("click",a)});const d=async({promise:s,spinner:t,className:n="is-hidden"})=>{t.classList.remove(n);const o=await s();return t.classList.add(n),o};
//# sourceMappingURL=commonHelpers.js.map
