import{a as L,S as v,i as u}from"./assets/vendor-89feecc5.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const g=document.querySelector(".gallery"),b=document.querySelector(".search-form"),m=document.querySelector(".loading"),c=document.querySelector(".btn-load"),l=document.querySelector(".btn-load-div"),w=L.create({baseURL:"https://pixabay.com/api/",params:{key:"41686068-f8a1ddec694d7ca7a5960473b",image_type:"photo",orientation:"horizontal",safesearch:!0}});function S(o=[]){const s=o.reduce((t,{largeImageURL:n,webformatURL:e,tags:r,likes:a,views:f,comments:h,downloads:y})=>t+`<li class="gallery-item">
    <a href=${n}> 
      <img class="gallery-img" src =${e} alt=${r}/>
    </a>
    <div class="gallery-text-box">
      <p>Likes: <span class="text-value">${a}</span></p>
      <p>views: <span class="text-value">${f}</span></p>
      <p>comments: <span class="text-value">${h}</span></p>
      <p>downloads: <span class="text-value">${y}</span></p>
  </div>
  </li>`,"");g.insertAdjacentHTML("beforeend",s),x.refresh()}const x=new v(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0}),q=async o=>{try{return(await w.get("",{params:o})).data}catch(s){console.error(s)}},H=o=>{let s=1,t=!1;const n=40;return async()=>{try{if(t)return;const{hits:e,totalHits:r}=await q({page:s,per_page:n,q:o});return s>=Math.ceil(r/n)&&(t=!0),s++,t&&r!=0&&(l.classList.add("is-hidden"),E()),r==0&&(l.classList.add("is-hidden"),P()),e}catch(e){console.error(e)}}};let i=null,d=null;b.addEventListener("submit",async o=>{o.preventDefault(),i!=null&&(c.removeEventListener("click",d),i=null);const t=new FormData(o.currentTarget).get("search").trim();if(g.innerHTML="",l.classList.add("is-hidden"),!t){$();return}l.classList.remove("is-hidden");const n=H(t);o.currentTarget.reset(),i=async()=>{const e=await p({promise:n,spinner:m});S(e)},await p({promise:i,spinner:m}),d=async()=>{await I({promise:i})},c.addEventListener("click",d)});const p=async({promise:o,spinner:s,className:t="is-hidden"})=>{s.classList.remove(t),c.classList.add(t);const n=await o();return s.classList.add(t),c.classList.remove(t),n},I=async({promise:o})=>{const t=document.querySelector(".gallery-item").getBoundingClientRect().height,n=document.documentElement.clientHeight;await o(),window.scrollBy({top:t*Math.floor(n/t),left:0,behavior:"smooth"})},$=()=>u.warning({position:"topRight",message:"Please, fill in the field!"}),E=()=>u.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),P=()=>u.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});
//# sourceMappingURL=commonHelpers.js.map
